Repository safiratyas/MP-AntrianDokter-BE, pull requests merged in 2022-09, with the labels that each got.

#1 Configurate Sequelize Database
  app/index.js
  app/models/admins.js
  app/models/doctors.js
  app/models/examinations.js
  app/models/genders.js
  app/models/patients.js
  app/models/queues.js
  app/plugin/checkPassword.js
  app/plugin/createToken.js
  app/plugin/decodeToken.js
  app/plugin/hashPassword.js
  app/plugin/index.js
  db/migrations/20220918150650-create-admins.js
  db/migrations/20220918150714-create-genders.js
  db/migrations/20220918150733-create-examinations.js
  db/migrations/20220918150753-create-doctors.js
  db/migrations/20220918150833-create-queues.js
  db/migrations/20220918150929-create-patients.js
  package.json
Labels: documentation

#5 Deployment
  .github/workflows/action.yml
  app/controllers/api/application.js
  app/repositories/admin.js
  app/router.js
  db/seeders/20220919050348-insert-admin.js
  db/seeders/20220919062500-insert-doctor.js
  db/seeders/20220919071402-insert-patient.js
Labels: help wanted

#6 Register & Login Endpoint
  .gitignore
  app/controllers/api/admins.js
  app/controllers/api/authentication.js
  app/controllers/api/index.js
  app/controllers/api/patients.js
  app/middlewares/adminAuthorization.js
  app/middlewares/adminCondition.js
  app/middlewares/index.js
  app/middlewares/patientAuthorization.js
  app/middlewares/patientCondition.js
  app/models/admins.js
  app/models/doctors.js
  app/models/examinations.js
  app/models/genders.js
  app/models/index.js
  app/models/patients.js
  app/models/queues.js
  app/repositories/admin.js
  app/repositories/admins.js
  app/repositories/patients.js
  app/router.js
  app/services/admins.js
  app/services/patients.js
  bin/www
  db/migrations/20220920023409-create-genders.js
  db/migrations/20220920023410-create-patients.js
  db/migrations/20220920023453-create-admins.js
  db/migrations/20220920023521-create-examinations.js
  db/migrations/20220920023542-create-doctors.js
  db/migrations/20220920023606-create-queues.js
Labels: bug, help wanted

#7 Seeders
  app/controllers/api/patients.js
  app/utils/timeFormat.js
  data/Mediq Backend.postman_collection.json
  db/migrations/20220920023410-create-patients.js
  db/seeders/20220919050347-insert-gender.js
  db/seeders/20220919050348-insert-admin.js
  db/seeders/20220919062414-insert-examination.js
  db/seeders/20220919062500-insert-doctor.js
  db/seeders/20220919071402-insert-patient.js
  db/seeders/20220921041236-insert-doctor.js
  db/seeders/20220921044622-insert-examination.js
  db/seeders/20220921045542-insert-gender.js
  db/seeders/20220921045824-insert-admin.js
  db/seeders/20220921061938-insert-patient.js
Labels: help wanted

#9 endpoint Doctors and Examinations
  app/controllers/api/doctors.js
  app/controllers/api/examinations.js
  app/router.js
  data/Mediq Backend.postman_collection.json
Labels: documentation

#11 endpoint getId Booking Number, getAll Booking Number, Update Readme, …
  README.md
  app/controllers/api/queue.js
  app/router.js
  erd.png
Labels: documentation

#13 History Patient & Delete Tables
  app/controllers/api/doctors.js
  app/controllers/api/index.js
  app/controllers/api/queue.js
  app/models/doctors.js
  app/models/polyclinics.js
  app/models/queues.js
  app/repositories/doctors.js
  app/router.js
  app/services/doctors.js
  config/swagger.json
  db/migrations/20220920023541-create-polyclinics.js
  db/migrations/20220920023542-create-doctors.js
  db/migrations/20220920023606-create-queues.js
  db/seeders/20220921041211-insert-polyclinic.js
  db/seeders/20220921041236-insert-doctor.js
Labels: enhancement
